#!/bin/sh
echo '* Backing up mce.ini'
mv /etc/mce/mce.ini /etc/mce/mce.ini.telescope.bak
echo '* Changing mce.ini'
sed -e 's/^HomeKeyShortAction/#HomeKeyShortAction/' </etc/mce/mce.ini.telescope.bak | sed -e 's/^HomeKeyLongAction/#HomeKeyLongAction/' | sed -e 's/^\[HomeKey\]/[HomeKey]\nHomeKeyShortAction=disabled\nHomeKeyLongAction=disabled/' >/etc/mce/mce.ini
echo '* Installing service'
update-rc.d telescope-svc defaults 99
echo '* Restarting MCE...'
/etc/init.d/mce restart
echo '* Starting Telescope...'
/etc/init.d/telescope-svc start

oldversion="$2"
if [ -z "$oldversion" ]; then
    maemo-confirm-text "Telescope" /usr/share/telescope/install-notice.txt
fi

exit 0
